apiVersion: v1
kind: Service
metadata:
  name: gw-service
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: gw-service
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: gw

---
apiVersion: v1
kind: Service
metadata:
  name: gw-ssl-service
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: gw-service-ssl
    port: 8443
    targetPort: 8443
    protocol: TCP
  selector:
    app: gw

---
apiVersion: v1
kind: Service
metadata:
  name: gw-admin-service
spec:
  type: ClusterIP
  ports:
  - name: gw-service-admin
    port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    app: gw

---
apiVersion: v1
kind: Service
metadata:
  name: gw-admin-ssl-service
spec:
  type: ClusterIP
  ports:
  - name: gw-service-admin-ssl
    port: 8444
    targetPort: 8444
    protocol: TCP
  selector:
    app: gw

---
apiVersion: v1
kind: Service
metadata:
  name: gw-ui-service
spec:
  type: ClusterIP
  ports:
  - name: gw-ui
    port: 1337
    targetPort: 1337
    protocol: TCP
  selector:
    app: gw-ui

---
apiVersion: v1
kind: Service
metadata:
  name: gw-admin-ui-service
spec:
  type: ClusterIP
  ports:
  - name: gw-admin-ui
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: gw-ui
