apiVersion: v1
kind: PersistentVolume
metadata:
  name: gw-db-pv
  labels:
    purpose: gw-db-pv-data
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/local-storage/pgsql-data"
