apiVersion: v1
kind: Service
metadata:
  name: micro-svc-service
spec:
  type: ClusterIP
  selector:
    deployment: micro-svc
  ports:
    -
      name: http-service
      protocol: TCP
      port: 8181
