apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gw-db-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      purpose: gw-db-pv-data
