apiVersion: v1
kind: Service
metadata:
  name: gw-db-pgsql-service
spec:
  type: ClusterIP
  selector:
    deployment: gw-db-pgsql
  ports:
  - name: pgsql-port
    port: 5432
    targetPort: 5432
    protocol: TCP
